spring:
  application:
    name: customer
  config:
    import: "configserver:http://localhost:8075/"
  profiles:
    active: default

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
endpoints:
  shutdown:
    enabled: true
