spring:
  application:
    name: ticketing
  config:
    import: "configserver:http://localhost:8075/"
  profiles:
    active: default
  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 1000

  ratelimiter:
    configs:
      default:
        timeout-duration: 1000
        limit-refresh-period: 5000
        limit-for-period: 2

management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

  health:
    liveness-state:
      enabled: true
    readiness-state: true

    endpoint:
      shutdown:
        enabled: true

endpoints:
  shutdown:
    enable: true

logging:
  level:
    com.uexcel: DEBUG





