spring:
  application:
    name: configserver

  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password: "guest"

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          force-pull: true
          timeout: 5
          uri: "https://github.com/Uexcel2022/ltts-config.git"
          clone-on-start: true
          default-label: main

server:
  port: 8075

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true



