spring:
  application:
    name: bus
  profiles:
    active: default
  config:
    import: "configserver:http://localhost:8075/"

  rabbitmq:
    host: localhost
    port: 5672
    username: "guest"
    password:  "guest"


management:
  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

endpoints:
  shutdown:
    enabled: true
logging:
  level:
    com.uexcel: DEBUG
